s3store: Allow `+` in object IDs
tus/tusd pull request #1123
Opened 2024-04-24 15:23 UTC by OwynWang

To be compatible with object id that contains `+` .

2024-04-25 06:20 UTC, Acconut commented
Thank you for this PR. I wonder if there are S3-compatible which include + in their multipart IDs. AWS does not do this as far as I know, but other implementations might differ. DigitalOcean Spaces includes ~ if I recall correctly.

2024-04-25 11:58 UTC, OwynWang commented
So we could not ensure whether object ID and multipart ID contains `+` or other special characters. Maybe we could encode these IDs use base64.

2024-04-25 12:23 UTC, OwynWang commented
Amend committed.

2024-05-02 08:56 UTC, Acconut commented
> Maybe we could encode these IDs use base64.

This has been discussed before, but also comes with downsides. It would be a breaking change as the URL format changes and some people depend on the format to extract the object ID. Switching to a base 64 encoding would breaking such integrations.

In addition, we want to move away from including the multipart ID entirely in the upload URL, as this prevents users from fully customizing the upload URL. It will also make the upload URL from the s3store similar to how all other storages work.

For that reason, I don't think we should invest more time into looking into base64 encoding IDs. Since I don't remember any S3 provider using `+` in multipart IDs, we can merge this for now. If people run into issues, we will revert it.

2024-05-02 08:57 UTC, Acconut requested changes
I just saw that you changed this PR to use base64 encoding. Please revert it to the original version where the last segment of the upload ID was used as the multipart ID. Then we can merge this.

2024-05-03 04:26 UTC, OwynWang commented
> I just saw that you changed this PR to use base64 encoding. Please revert it to the original version where the last segment of the upload ID was used as the multipart ID. Then we can merge this.
OK, reverted.

2024-05-06 07:24 UTC, Acconut approved these changes

2024-05-06 08:47 UTC, Acconut approved these changes
Thank you! I added a test case to ensure that this works and keeps working.

2024-05-06 08:47 UTC, merged